// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportTicketMessageUpdate is the builder for updating SupportTicketMessage entities.
type SupportTicketMessageUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketMessageMutation
}

// Where appends a list predicates to the SupportTicketMessageUpdate builder.
func (_u *SupportTicketMessageUpdate) Where(ps ...predicate.SupportTicketMessage) *SupportTicketMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *SupportTicketMessageUpdate) SetTicketID(v int64) *SupportTicketMessageUpdate {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableTicketID(v *int64) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetAuthorUserID sets the "author_user_id" field.
func (_u *SupportTicketMessageUpdate) SetAuthorUserID(v int64) *SupportTicketMessageUpdate {
	_u.mutation.SetAuthorUserID(v)
	return _u
}

// SetNillableAuthorUserID sets the "author_user_id" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableAuthorUserID(v *int64) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetAuthorUserID(*v)
	}
	return _u
}

// SetAuthorRole sets the "author_role" field.
func (_u *SupportTicketMessageUpdate) SetAuthorRole(v string) *SupportTicketMessageUpdate {
	_u.mutation.SetAuthorRole(v)
	return _u
}

// SetNillableAuthorRole sets the "author_role" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableAuthorRole(v *string) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetAuthorRole(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *SupportTicketMessageUpdate) SetBody(v string) *SupportTicketMessageUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableBody(v *string) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetTicket sets the "ticket" edge to the SupportTicket entity.
func (_u *SupportTicketMessageUpdate) SetTicket(v *SupportTicket) *SupportTicketMessageUpdate {
	return _u.SetTicketID(v.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *SupportTicketMessageUpdate) SetAuthorID(id int64) *SupportTicketMessageUpdate {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *SupportTicketMessageUpdate) SetAuthor(v *User) *SupportTicketMessageUpdate {
	return _u.SetAuthorID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the SupportTicketAttachment entity by IDs.
func (_u *SupportTicketMessageUpdate) AddAttachmentIDs(ids ...int64) *SupportTicketMessageUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the SupportTicketAttachment entity.
func (_u *SupportTicketMessageUpdate) AddAttachments(v ...*SupportTicketAttachment) *SupportTicketMessageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the SupportTicketMessageMutation object of the builder.
func (_u *SupportTicketMessageUpdate) Mutation() *SupportTicketMessageMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the SupportTicket entity.
func (_u *SupportTicketMessageUpdate) ClearTicket() *SupportTicketMessageUpdate {
	_u.mutation.ClearTicket()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *SupportTicketMessageUpdate) ClearAuthor() *SupportTicketMessageUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearAttachments clears all "attachments" edges to the SupportTicketAttachment entity.
func (_u *SupportTicketMessageUpdate) ClearAttachments() *SupportTicketMessageUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to SupportTicketAttachment entities by IDs.
func (_u *SupportTicketMessageUpdate) RemoveAttachmentIDs(ids ...int64) *SupportTicketMessageUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to SupportTicketAttachment entities.
func (_u *SupportTicketMessageUpdate) RemoveAttachments(v ...*SupportTicketAttachment) *SupportTicketMessageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketMessageUpdate) check() error {
	if v, ok := _u.mutation.AuthorRole(); ok {
		if err := supportticketmessage.AuthorRoleValidator(v); err != nil {
			return &ValidationError{Name: "author_role", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.author_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := supportticketmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.body": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketMessage.ticket"`)
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketMessage.author"`)
	}
	return nil
}

func (_u *SupportTicketMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketmessage.Table, supportticketmessage.Columns, sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AuthorRole(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(supportticketmessage.FieldBody, field.TypeString, value)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.TicketTable,
			Columns: []string{supportticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.TicketTable,
			Columns: []string{supportticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.AuthorTable,
			Columns: []string{supportticketmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.AuthorTable,
			Columns: []string{supportticketmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticketmessage.AttachmentsTable,
			Columns: []string{supportticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticketmessage.AttachmentsTable,
			Columns: []string{supportticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticketmessage.AttachmentsTable,
			Columns: []string{supportticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketMessageUpdateOne is the builder for updating a single SupportTicketMessage entity.
type SupportTicketMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketMessageMutation
}

// SetTicketID sets the "ticket_id" field.
func (_u *SupportTicketMessageUpdateOne) SetTicketID(v int64) *SupportTicketMessageUpdateOne {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableTicketID(v *int64) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetAuthorUserID sets the "author_user_id" field.
func (_u *SupportTicketMessageUpdateOne) SetAuthorUserID(v int64) *SupportTicketMessageUpdateOne {
	_u.mutation.SetAuthorUserID(v)
	return _u
}

// SetNillableAuthorUserID sets the "author_user_id" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableAuthorUserID(v *int64) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetAuthorUserID(*v)
	}
	return _u
}

// SetAuthorRole sets the "author_role" field.
func (_u *SupportTicketMessageUpdateOne) SetAuthorRole(v string) *SupportTicketMessageUpdateOne {
	_u.mutation.SetAuthorRole(v)
	return _u
}

// SetNillableAuthorRole sets the "author_role" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableAuthorRole(v *string) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetAuthorRole(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *SupportTicketMessageUpdateOne) SetBody(v string) *SupportTicketMessageUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableBody(v *string) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetTicket sets the "ticket" edge to the SupportTicket entity.
func (_u *SupportTicketMessageUpdateOne) SetTicket(v *SupportTicket) *SupportTicketMessageUpdateOne {
	return _u.SetTicketID(v.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *SupportTicketMessageUpdateOne) SetAuthorID(id int64) *SupportTicketMessageUpdateOne {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *SupportTicketMessageUpdateOne) SetAuthor(v *User) *SupportTicketMessageUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the SupportTicketAttachment entity by IDs.
func (_u *SupportTicketMessageUpdateOne) AddAttachmentIDs(ids ...int64) *SupportTicketMessageUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the SupportTicketAttachment entity.
func (_u *SupportTicketMessageUpdateOne) AddAttachments(v ...*SupportTicketAttachment) *SupportTicketMessageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the SupportTicketMessageMutation object of the builder.
func (_u *SupportTicketMessageUpdateOne) Mutation() *SupportTicketMessageMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the SupportTicket entity.
func (_u *SupportTicketMessageUpdateOne) ClearTicket() *SupportTicketMessageUpdateOne {
	_u.mutation.ClearTicket()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *SupportTicketMessageUpdateOne) ClearAuthor() *SupportTicketMessageUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearAttachments clears all "attachments" edges to the SupportTicketAttachment entity.
func (_u *SupportTicketMessageUpdateOne) ClearAttachments() *SupportTicketMessageUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to SupportTicketAttachment entities by IDs.
func (_u *SupportTicketMessageUpdateOne) RemoveAttachmentIDs(ids ...int64) *SupportTicketMessageUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to SupportTicketAttachment entities.
func (_u *SupportTicketMessageUpdateOne) RemoveAttachments(v ...*SupportTicketAttachment) *SupportTicketMessageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Where appends a list predicates to the SupportTicketMessageUpdate builder.
func (_u *SupportTicketMessageUpdateOne) Where(ps ...predicate.SupportTicketMessage) *SupportTicketMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketMessageUpdateOne) Select(field string, fields ...string) *SupportTicketMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicketMessage entity.
func (_u *SupportTicketMessageUpdateOne) Save(ctx context.Context) (*SupportTicketMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketMessageUpdateOne) SaveX(ctx context.Context) *SupportTicketMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketMessageUpdateOne) check() error {
	if v, ok := _u.mutation.AuthorRole(); ok {
		if err := supportticketmessage.AuthorRoleValidator(v); err != nil {
			return &ValidationError{Name: "author_role", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.author_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := supportticketmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.body": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketMessage.ticket"`)
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketMessage.author"`)
	}
	return nil
}

func (_u *SupportTicketMessageUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicketMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketmessage.Table, supportticketmessage.Columns, sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicketMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticketmessage.FieldID)
		for _, f := range fields {
			if !supportticketmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticketmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AuthorRole(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(supportticketmessage.FieldBody, field.TypeString, value)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.TicketTable,
			Columns: []string{supportticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.TicketTable,
			Columns: []string{supportticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.AuthorTable,
			Columns: []string{supportticketmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.AuthorTable,
			Columns: []string{supportticketmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticketmessage.AttachmentsTable,
			Columns: []string{supportticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticketmessage.AttachmentsTable,
			Columns: []string{supportticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticketmessage.AttachmentsTable,
			Columns: []string{supportticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportTicketMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
