// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportTicketRead is the model entity for the SupportTicketRead schema.
type SupportTicketRead struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TicketID holds the value of the "ticket_id" field.
	TicketID int64 `json:"ticket_id,omitempty"`
	// ReaderUserID holds the value of the "reader_user_id" field.
	ReaderUserID int64 `json:"reader_user_id,omitempty"`
	// ReaderRole holds the value of the "reader_role" field.
	ReaderRole string `json:"reader_role,omitempty"`
	// LastReadMessageID holds the value of the "last_read_message_id" field.
	LastReadMessageID int64 `json:"last_read_message_id,omitempty"`
	// ReadAt holds the value of the "read_at" field.
	ReadAt time.Time `json:"read_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupportTicketReadQuery when eager-loading is set.
	Edges        SupportTicketReadEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SupportTicketReadEdges holds the relations/edges for other nodes in the graph.
type SupportTicketReadEdges struct {
	// Ticket holds the value of the ticket edge.
	Ticket *SupportTicket `json:"ticket,omitempty"`
	// Reader holds the value of the reader edge.
	Reader *User `json:"reader,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TicketOrErr returns the Ticket value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportTicketReadEdges) TicketOrErr() (*SupportTicket, error) {
	if e.Ticket != nil {
		return e.Ticket, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: supportticket.Label}
	}
	return nil, &NotLoadedError{edge: "ticket"}
}

// ReaderOrErr returns the Reader value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportTicketReadEdges) ReaderOrErr() (*User, error) {
	if e.Reader != nil {
		return e.Reader, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "reader"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupportTicketRead) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supportticketread.FieldID, supportticketread.FieldTicketID, supportticketread.FieldReaderUserID, supportticketread.FieldLastReadMessageID:
			values[i] = new(sql.NullInt64)
		case supportticketread.FieldReaderRole:
			values[i] = new(sql.NullString)
		case supportticketread.FieldReadAt, supportticketread.FieldCreatedAt, supportticketread.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupportTicketRead fields.
func (_m *SupportTicketRead) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supportticketread.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case supportticketread.FieldTicketID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_id", values[i])
			} else if value.Valid {
				_m.TicketID = value.Int64
			}
		case supportticketread.FieldReaderUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reader_user_id", values[i])
			} else if value.Valid {
				_m.ReaderUserID = value.Int64
			}
		case supportticketread.FieldReaderRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reader_role", values[i])
			} else if value.Valid {
				_m.ReaderRole = value.String
			}
		case supportticketread.FieldLastReadMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_read_message_id", values[i])
			} else if value.Valid {
				_m.LastReadMessageID = value.Int64
			}
		case supportticketread.FieldReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field read_at", values[i])
			} else if value.Valid {
				_m.ReadAt = value.Time
			}
		case supportticketread.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case supportticketread.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupportTicketRead.
// This includes values selected through modifiers, order, etc.
func (_m *SupportTicketRead) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTicket queries the "ticket" edge of the SupportTicketRead entity.
func (_m *SupportTicketRead) QueryTicket() *SupportTicketQuery {
	return NewSupportTicketReadClient(_m.config).QueryTicket(_m)
}

// QueryReader queries the "reader" edge of the SupportTicketRead entity.
func (_m *SupportTicketRead) QueryReader() *UserQuery {
	return NewSupportTicketReadClient(_m.config).QueryReader(_m)
}

// Update returns a builder for updating this SupportTicketRead.
// Note that you need to call SupportTicketRead.Unwrap() before calling this method if this SupportTicketRead
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupportTicketRead) Update() *SupportTicketReadUpdateOne {
	return NewSupportTicketReadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupportTicketRead entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupportTicketRead) Unwrap() *SupportTicketRead {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupportTicketRead is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupportTicketRead) String() string {
	var builder strings.Builder
	builder.WriteString("SupportTicketRead(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ticket_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TicketID))
	builder.WriteString(", ")
	builder.WriteString("reader_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReaderUserID))
	builder.WriteString(", ")
	builder.WriteString("reader_role=")
	builder.WriteString(_m.ReaderRole)
	builder.WriteString(", ")
	builder.WriteString("last_read_message_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastReadMessageID))
	builder.WriteString(", ")
	builder.WriteString("read_at=")
	builder.WriteString(_m.ReadAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupportTicketReads is a parsable slice of SupportTicketRead.
type SupportTicketReads []*SupportTicketRead
