// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportTicketReadQuery is the builder for querying SupportTicketRead entities.
type SupportTicketReadQuery struct {
	config
	ctx        *QueryContext
	order      []supportticketread.OrderOption
	inters     []Interceptor
	predicates []predicate.SupportTicketRead
	withTicket *SupportTicketQuery
	withReader *UserQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SupportTicketReadQuery builder.
func (_q *SupportTicketReadQuery) Where(ps ...predicate.SupportTicketRead) *SupportTicketReadQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SupportTicketReadQuery) Limit(limit int) *SupportTicketReadQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SupportTicketReadQuery) Offset(offset int) *SupportTicketReadQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SupportTicketReadQuery) Unique(unique bool) *SupportTicketReadQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SupportTicketReadQuery) Order(o ...supportticketread.OrderOption) *SupportTicketReadQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTicket chains the current query on the "ticket" edge.
func (_q *SupportTicketReadQuery) QueryTicket() *SupportTicketQuery {
	query := (&SupportTicketClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(supportticketread.Table, supportticketread.FieldID, selector),
			sqlgraph.To(supportticket.Table, supportticket.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, supportticketread.TicketTable, supportticketread.TicketColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReader chains the current query on the "reader" edge.
func (_q *SupportTicketReadQuery) QueryReader() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(supportticketread.Table, supportticketread.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, supportticketread.ReaderTable, supportticketread.ReaderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SupportTicketRead entity from the query.
// Returns a *NotFoundError when no SupportTicketRead was found.
func (_q *SupportTicketReadQuery) First(ctx context.Context) (*SupportTicketRead, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{supportticketread.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SupportTicketReadQuery) FirstX(ctx context.Context) *SupportTicketRead {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SupportTicketRead ID from the query.
// Returns a *NotFoundError when no SupportTicketRead ID was found.
func (_q *SupportTicketReadQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{supportticketread.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SupportTicketReadQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SupportTicketRead entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SupportTicketRead entity is found.
// Returns a *NotFoundError when no SupportTicketRead entities are found.
func (_q *SupportTicketReadQuery) Only(ctx context.Context) (*SupportTicketRead, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{supportticketread.Label}
	default:
		return nil, &NotSingularError{supportticketread.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SupportTicketReadQuery) OnlyX(ctx context.Context) *SupportTicketRead {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SupportTicketRead ID in the query.
// Returns a *NotSingularError when more than one SupportTicketRead ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SupportTicketReadQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{supportticketread.Label}
	default:
		err = &NotSingularError{supportticketread.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SupportTicketReadQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SupportTicketReads.
func (_q *SupportTicketReadQuery) All(ctx context.Context) ([]*SupportTicketRead, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SupportTicketRead, *SupportTicketReadQuery]()
	return withInterceptors[[]*SupportTicketRead](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SupportTicketReadQuery) AllX(ctx context.Context) []*SupportTicketRead {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SupportTicketRead IDs.
func (_q *SupportTicketReadQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(supportticketread.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SupportTicketReadQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SupportTicketReadQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SupportTicketReadQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SupportTicketReadQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SupportTicketReadQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SupportTicketReadQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SupportTicketReadQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SupportTicketReadQuery) Clone() *SupportTicketReadQuery {
	if _q == nil {
		return nil
	}
	return &SupportTicketReadQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]supportticketread.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.SupportTicketRead{}, _q.predicates...),
		withTicket: _q.withTicket.Clone(),
		withReader: _q.withReader.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTicket tells the query-builder to eager-load the nodes that are connected to
// the "ticket" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SupportTicketReadQuery) WithTicket(opts ...func(*SupportTicketQuery)) *SupportTicketReadQuery {
	query := (&SupportTicketClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTicket = query
	return _q
}

// WithReader tells the query-builder to eager-load the nodes that are connected to
// the "reader" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SupportTicketReadQuery) WithReader(opts ...func(*UserQuery)) *SupportTicketReadQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReader = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TicketID int64 `json:"ticket_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SupportTicketRead.Query().
//		GroupBy(supportticketread.FieldTicketID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SupportTicketReadQuery) GroupBy(field string, fields ...string) *SupportTicketReadGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SupportTicketReadGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = supportticketread.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TicketID int64 `json:"ticket_id,omitempty"`
//	}
//
//	client.SupportTicketRead.Query().
//		Select(supportticketread.FieldTicketID).
//		Scan(ctx, &v)
func (_q *SupportTicketReadQuery) Select(fields ...string) *SupportTicketReadSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SupportTicketReadSelect{SupportTicketReadQuery: _q}
	sbuild.label = supportticketread.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SupportTicketReadSelect configured with the given aggregations.
func (_q *SupportTicketReadQuery) Aggregate(fns ...AggregateFunc) *SupportTicketReadSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SupportTicketReadQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !supportticketread.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SupportTicketReadQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SupportTicketRead, error) {
	var (
		nodes       = []*SupportTicketRead{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withTicket != nil,
			_q.withReader != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SupportTicketRead).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SupportTicketRead{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTicket; query != nil {
		if err := _q.loadTicket(ctx, query, nodes, nil,
			func(n *SupportTicketRead, e *SupportTicket) { n.Edges.Ticket = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withReader; query != nil {
		if err := _q.loadReader(ctx, query, nodes, nil,
			func(n *SupportTicketRead, e *User) { n.Edges.Reader = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SupportTicketReadQuery) loadTicket(ctx context.Context, query *SupportTicketQuery, nodes []*SupportTicketRead, init func(*SupportTicketRead), assign func(*SupportTicketRead, *SupportTicket)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SupportTicketRead)
	for i := range nodes {
		fk := nodes[i].TicketID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(supportticket.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ticket_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SupportTicketReadQuery) loadReader(ctx context.Context, query *UserQuery, nodes []*SupportTicketRead, init func(*SupportTicketRead), assign func(*SupportTicketRead, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SupportTicketRead)
	for i := range nodes {
		fk := nodes[i].ReaderUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "reader_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SupportTicketReadQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SupportTicketReadQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(supportticketread.Table, supportticketread.Columns, sqlgraph.NewFieldSpec(supportticketread.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticketread.FieldID)
		for i := range fields {
			if fields[i] != supportticketread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTicket != nil {
			_spec.Node.AddColumnOnce(supportticketread.FieldTicketID)
		}
		if _q.withReader != nil {
			_spec.Node.AddColumnOnce(supportticketread.FieldReaderUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SupportTicketReadQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(supportticketread.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = supportticketread.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SupportTicketReadQuery) ForUpdate(opts ...sql.LockOption) *SupportTicketReadQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SupportTicketReadQuery) ForShare(opts ...sql.LockOption) *SupportTicketReadQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// SupportTicketReadGroupBy is the group-by builder for SupportTicketRead entities.
type SupportTicketReadGroupBy struct {
	selector
	build *SupportTicketReadQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SupportTicketReadGroupBy) Aggregate(fns ...AggregateFunc) *SupportTicketReadGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SupportTicketReadGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SupportTicketReadQuery, *SupportTicketReadGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SupportTicketReadGroupBy) sqlScan(ctx context.Context, root *SupportTicketReadQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SupportTicketReadSelect is the builder for selecting fields of SupportTicketRead entities.
type SupportTicketReadSelect struct {
	*SupportTicketReadQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SupportTicketReadSelect) Aggregate(fns ...AggregateFunc) *SupportTicketReadSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SupportTicketReadSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SupportTicketReadQuery, *SupportTicketReadSelect](ctx, _s.SupportTicketReadQuery, _s, _s.inters, v)
}

func (_s *SupportTicketReadSelect) sqlScan(ctx context.Context, root *SupportTicketReadQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
