// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/supportticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
)

// SupportTicketAttachmentCreate is the builder for creating a SupportTicketAttachment entity.
type SupportTicketAttachmentCreate struct {
	config
	mutation *SupportTicketAttachmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMessageID sets the "message_id" field.
func (_c *SupportTicketAttachmentCreate) SetMessageID(v int64) *SupportTicketAttachmentCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetData sets the "data" field.
func (_c *SupportTicketAttachmentCreate) SetData(v []byte) *SupportTicketAttachmentCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *SupportTicketAttachmentCreate) SetContentType(v string) *SupportTicketAttachmentCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *SupportTicketAttachmentCreate) SetSizeBytes(v int64) *SupportTicketAttachmentCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetWidth sets the "width" field.
func (_c *SupportTicketAttachmentCreate) SetWidth(v int) *SupportTicketAttachmentCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *SupportTicketAttachmentCreate) SetNillableWidth(v *int) *SupportTicketAttachmentCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *SupportTicketAttachmentCreate) SetHeight(v int) *SupportTicketAttachmentCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *SupportTicketAttachmentCreate) SetNillableHeight(v *int) *SupportTicketAttachmentCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupportTicketAttachmentCreate) SetCreatedAt(v time.Time) *SupportTicketAttachmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupportTicketAttachmentCreate) SetNillableCreatedAt(v *time.Time) *SupportTicketAttachmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetMessage sets the "message" edge to the SupportTicketMessage entity.
func (_c *SupportTicketAttachmentCreate) SetMessage(v *SupportTicketMessage) *SupportTicketAttachmentCreate {
	return _c.SetMessageID(v.ID)
}

// Mutation returns the SupportTicketAttachmentMutation object of the builder.
func (_c *SupportTicketAttachmentCreate) Mutation() *SupportTicketAttachmentMutation {
	return _c.mutation
}

// Save creates the SupportTicketAttachment in the database.
func (_c *SupportTicketAttachmentCreate) Save(ctx context.Context) (*SupportTicketAttachment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupportTicketAttachmentCreate) SaveX(ctx context.Context) *SupportTicketAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportTicketAttachmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportTicketAttachmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupportTicketAttachmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := supportticketattachment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupportTicketAttachmentCreate) check() error {
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "SupportTicketAttachment.message_id"`)}
	}
	if _, ok := _c.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "SupportTicketAttachment.data"`)}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "SupportTicketAttachment.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := supportticketattachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "SupportTicketAttachment.size_bytes"`)}
	}
	if v, ok := _c.mutation.SizeBytes(); ok {
		if err := supportticketattachment.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.size_bytes": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Width(); ok {
		if err := supportticketattachment.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.width": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Height(); ok {
		if err := supportticketattachment.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.height": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupportTicketAttachment.created_at"`)}
	}
	if len(_c.mutation.MessageIDs()) == 0 {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required edge "SupportTicketAttachment.message"`)}
	}
	return nil
}

func (_c *SupportTicketAttachmentCreate) sqlSave(ctx context.Context) (*SupportTicketAttachment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupportTicketAttachmentCreate) createSpec() (*SupportTicketAttachment, *sqlgraph.CreateSpec) {
	var (
		_node = &SupportTicketAttachment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supportticketattachment.Table, sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(supportticketattachment.FieldData, field.TypeBytes, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(supportticketattachment.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(supportticketattachment.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(supportticketattachment.FieldWidth, field.TypeInt, value)
		_node.Width = &value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(supportticketattachment.FieldHeight, field.TypeInt, value)
		_node.Height = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supportticketattachment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.MessageTable,
			Columns: []string{supportticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportTicketAttachment.Create().
//		SetMessageID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportTicketAttachmentUpsert) {
//			SetMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportTicketAttachmentCreate) OnConflict(opts ...sql.ConflictOption) *SupportTicketAttachmentUpsertOne {
	_c.conflict = opts
	return &SupportTicketAttachmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportTicketAttachmentCreate) OnConflictColumns(columns ...string) *SupportTicketAttachmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportTicketAttachmentUpsertOne{
		create: _c,
	}
}

type (
	// SupportTicketAttachmentUpsertOne is the builder for "upsert"-ing
	//  one SupportTicketAttachment node.
	SupportTicketAttachmentUpsertOne struct {
		create *SupportTicketAttachmentCreate
	}

	// SupportTicketAttachmentUpsert is the "OnConflict" setter.
	SupportTicketAttachmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetMessageID sets the "message_id" field.
func (u *SupportTicketAttachmentUpsert) SetMessageID(v int64) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldMessageID, v)
	return u
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateMessageID() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldMessageID)
	return u
}

// SetData sets the "data" field.
func (u *SupportTicketAttachmentUpsert) SetData(v []byte) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateData() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldData)
	return u
}

// SetContentType sets the "content_type" field.
func (u *SupportTicketAttachmentUpsert) SetContentType(v string) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldContentType, v)
	return u
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateContentType() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldContentType)
	return u
}

// SetSizeBytes sets the "size_bytes" field.
func (u *SupportTicketAttachmentUpsert) SetSizeBytes(v int64) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldSizeBytes, v)
	return u
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateSizeBytes() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldSizeBytes)
	return u
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *SupportTicketAttachmentUpsert) AddSizeBytes(v int64) *SupportTicketAttachmentUpsert {
	u.Add(supportticketattachment.FieldSizeBytes, v)
	return u
}

// SetWidth sets the "width" field.
func (u *SupportTicketAttachmentUpsert) SetWidth(v int) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateWidth() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *SupportTicketAttachmentUpsert) AddWidth(v int) *SupportTicketAttachmentUpsert {
	u.Add(supportticketattachment.FieldWidth, v)
	return u
}

// ClearWidth clears the value of the "width" field.
func (u *SupportTicketAttachmentUpsert) ClearWidth() *SupportTicketAttachmentUpsert {
	u.SetNull(supportticketattachment.FieldWidth)
	return u
}

// SetHeight sets the "height" field.
func (u *SupportTicketAttachmentUpsert) SetHeight(v int) *SupportTicketAttachmentUpsert {
	u.Set(supportticketattachment.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsert) UpdateHeight() *SupportTicketAttachmentUpsert {
	u.SetExcluded(supportticketattachment.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *SupportTicketAttachmentUpsert) AddHeight(v int) *SupportTicketAttachmentUpsert {
	u.Add(supportticketattachment.FieldHeight, v)
	return u
}

// ClearHeight clears the value of the "height" field.
func (u *SupportTicketAttachmentUpsert) ClearHeight() *SupportTicketAttachmentUpsert {
	u.SetNull(supportticketattachment.FieldHeight)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportTicketAttachmentUpsertOne) UpdateNewValues() *SupportTicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(supportticketattachment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupportTicketAttachmentUpsertOne) Ignore() *SupportTicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportTicketAttachmentUpsertOne) DoNothing() *SupportTicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportTicketAttachmentCreate.OnConflict
// documentation for more info.
func (u *SupportTicketAttachmentUpsertOne) Update(set func(*SupportTicketAttachmentUpsert)) *SupportTicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportTicketAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetMessageID sets the "message_id" field.
func (u *SupportTicketAttachmentUpsertOne) SetMessageID(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateMessageID() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateMessageID()
	})
}

// SetData sets the "data" field.
func (u *SupportTicketAttachmentUpsertOne) SetData(v []byte) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateData() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateData()
	})
}

// SetContentType sets the "content_type" field.
func (u *SupportTicketAttachmentUpsertOne) SetContentType(v string) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateContentType() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateContentType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *SupportTicketAttachmentUpsertOne) SetSizeBytes(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *SupportTicketAttachmentUpsertOne) AddSizeBytes(v int64) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateSizeBytes() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetWidth sets the "width" field.
func (u *SupportTicketAttachmentUpsertOne) SetWidth(v int) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *SupportTicketAttachmentUpsertOne) AddWidth(v int) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateWidth() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateWidth()
	})
}

// ClearWidth clears the value of the "width" field.
func (u *SupportTicketAttachmentUpsertOne) ClearWidth() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearWidth()
	})
}

// SetHeight sets the "height" field.
func (u *SupportTicketAttachmentUpsertOne) SetHeight(v int) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *SupportTicketAttachmentUpsertOne) AddHeight(v int) *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertOne) UpdateHeight() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateHeight()
	})
}

// ClearHeight clears the value of the "height" field.
func (u *SupportTicketAttachmentUpsertOne) ClearHeight() *SupportTicketAttachmentUpsertOne {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearHeight()
	})
}

// Exec executes the query.
func (u *SupportTicketAttachmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportTicketAttachmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportTicketAttachmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupportTicketAttachmentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupportTicketAttachmentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupportTicketAttachmentCreateBulk is the builder for creating many SupportTicketAttachment entities in bulk.
type SupportTicketAttachmentCreateBulk struct {
	config
	err      error
	builders []*SupportTicketAttachmentCreate
	conflict []sql.ConflictOption
}

// Save creates the SupportTicketAttachment entities in the database.
func (_c *SupportTicketAttachmentCreateBulk) Save(ctx context.Context) ([]*SupportTicketAttachment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupportTicketAttachment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupportTicketAttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupportTicketAttachmentCreateBulk) SaveX(ctx context.Context) []*SupportTicketAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportTicketAttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportTicketAttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportTicketAttachment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportTicketAttachmentUpsert) {
//			SetMessageID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportTicketAttachmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupportTicketAttachmentUpsertBulk {
	_c.conflict = opts
	return &SupportTicketAttachmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportTicketAttachmentCreateBulk) OnConflictColumns(columns ...string) *SupportTicketAttachmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportTicketAttachmentUpsertBulk{
		create: _c,
	}
}

// SupportTicketAttachmentUpsertBulk is the builder for "upsert"-ing
// a bulk of SupportTicketAttachment nodes.
type SupportTicketAttachmentUpsertBulk struct {
	create *SupportTicketAttachmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportTicketAttachmentUpsertBulk) UpdateNewValues() *SupportTicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(supportticketattachment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportTicketAttachment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupportTicketAttachmentUpsertBulk) Ignore() *SupportTicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportTicketAttachmentUpsertBulk) DoNothing() *SupportTicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportTicketAttachmentCreateBulk.OnConflict
// documentation for more info.
func (u *SupportTicketAttachmentUpsertBulk) Update(set func(*SupportTicketAttachmentUpsert)) *SupportTicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportTicketAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetMessageID sets the "message_id" field.
func (u *SupportTicketAttachmentUpsertBulk) SetMessageID(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateMessageID() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateMessageID()
	})
}

// SetData sets the "data" field.
func (u *SupportTicketAttachmentUpsertBulk) SetData(v []byte) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateData() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateData()
	})
}

// SetContentType sets the "content_type" field.
func (u *SupportTicketAttachmentUpsertBulk) SetContentType(v string) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateContentType() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateContentType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *SupportTicketAttachmentUpsertBulk) SetSizeBytes(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *SupportTicketAttachmentUpsertBulk) AddSizeBytes(v int64) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateSizeBytes() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetWidth sets the "width" field.
func (u *SupportTicketAttachmentUpsertBulk) SetWidth(v int) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *SupportTicketAttachmentUpsertBulk) AddWidth(v int) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateWidth() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateWidth()
	})
}

// ClearWidth clears the value of the "width" field.
func (u *SupportTicketAttachmentUpsertBulk) ClearWidth() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearWidth()
	})
}

// SetHeight sets the "height" field.
func (u *SupportTicketAttachmentUpsertBulk) SetHeight(v int) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *SupportTicketAttachmentUpsertBulk) AddHeight(v int) *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *SupportTicketAttachmentUpsertBulk) UpdateHeight() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.UpdateHeight()
	})
}

// ClearHeight clears the value of the "height" field.
func (u *SupportTicketAttachmentUpsertBulk) ClearHeight() *SupportTicketAttachmentUpsertBulk {
	return u.Update(func(s *SupportTicketAttachmentUpsert) {
		s.ClearHeight()
	})
}

// Exec executes the query.
func (u *SupportTicketAttachmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupportTicketAttachmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportTicketAttachmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportTicketAttachmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
