// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/supportticketread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportTicketCreate is the builder for creating a SupportTicket entity.
type SupportTicketCreate struct {
	config
	mutation *SupportTicketMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *SupportTicketCreate) SetUserID(v int64) *SupportTicketCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *SupportTicketCreate) SetTitle(v string) *SupportTicketCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *SupportTicketCreate) SetCategory(v string) *SupportTicketCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *SupportTicketCreate) SetPriority(v string) *SupportTicketCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *SupportTicketCreate) SetNillablePriority(v *string) *SupportTicketCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SupportTicketCreate) SetStatus(v string) *SupportTicketCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SupportTicketCreate) SetNillableStatus(v *string) *SupportTicketCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupportTicketCreate) SetCreatedAt(v time.Time) *SupportTicketCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupportTicketCreate) SetNillableCreatedAt(v *time.Time) *SupportTicketCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SupportTicketCreate) SetUpdatedAt(v time.Time) *SupportTicketCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SupportTicketCreate) SetNillableUpdatedAt(v *time.Time) *SupportTicketCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SupportTicketCreate) SetUser(v *User) *SupportTicketCreate {
	return _c.SetUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the SupportTicketMessage entity by IDs.
func (_c *SupportTicketCreate) AddMessageIDs(ids ...int64) *SupportTicketCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the SupportTicketMessage entity.
func (_c *SupportTicketCreate) AddMessages(v ...*SupportTicketMessage) *SupportTicketCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// AddReadIDs adds the "reads" edge to the SupportTicketRead entity by IDs.
func (_c *SupportTicketCreate) AddReadIDs(ids ...int64) *SupportTicketCreate {
	_c.mutation.AddReadIDs(ids...)
	return _c
}

// AddReads adds the "reads" edges to the SupportTicketRead entity.
func (_c *SupportTicketCreate) AddReads(v ...*SupportTicketRead) *SupportTicketCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReadIDs(ids...)
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_c *SupportTicketCreate) Mutation() *SupportTicketMutation {
	return _c.mutation
}

// Save creates the SupportTicket in the database.
func (_c *SupportTicketCreate) Save(ctx context.Context) (*SupportTicket, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupportTicketCreate) SaveX(ctx context.Context) *SupportTicket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportTicketCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportTicketCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupportTicketCreate) defaults() {
	if _, ok := _c.mutation.Priority(); !ok {
		v := supportticket.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := supportticket.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := supportticket.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := supportticket.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupportTicketCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SupportTicket.user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "SupportTicket.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := supportticket.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "SupportTicket.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := supportticket.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "SupportTicket.priority"`)}
	}
	if v, ok := _c.mutation.Priority(); ok {
		if err := supportticket.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.priority": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SupportTicket.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupportTicket.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SupportTicket.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SupportTicket.user"`)}
	}
	return nil
}

func (_c *SupportTicketCreate) sqlSave(ctx context.Context) (*SupportTicket, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupportTicketCreate) createSpec() (*SupportTicket, *sqlgraph.CreateSpec) {
	var (
		_node = &SupportTicket{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supportticket.Table, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(supportticket.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(supportticket.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(supportticket.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supportticket.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.UserTable,
			Columns: []string{supportticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.ReadsTable,
			Columns: []string{supportticket.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketread.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportTicket.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportTicketUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportTicketCreate) OnConflict(opts ...sql.ConflictOption) *SupportTicketUpsertOne {
	_c.conflict = opts
	return &SupportTicketUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportTicket.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportTicketCreate) OnConflictColumns(columns ...string) *SupportTicketUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportTicketUpsertOne{
		create: _c,
	}
}

type (
	// SupportTicketUpsertOne is the builder for "upsert"-ing
	//  one SupportTicket node.
	SupportTicketUpsertOne struct {
		create *SupportTicketCreate
	}

	// SupportTicketUpsert is the "OnConflict" setter.
	SupportTicketUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *SupportTicketUpsert) SetUserID(v int64) *SupportTicketUpsert {
	u.Set(supportticket.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SupportTicketUpsert) UpdateUserID() *SupportTicketUpsert {
	u.SetExcluded(supportticket.FieldUserID)
	return u
}

// SetTitle sets the "title" field.
func (u *SupportTicketUpsert) SetTitle(v string) *SupportTicketUpsert {
	u.Set(supportticket.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SupportTicketUpsert) UpdateTitle() *SupportTicketUpsert {
	u.SetExcluded(supportticket.FieldTitle)
	return u
}

// SetCategory sets the "category" field.
func (u *SupportTicketUpsert) SetCategory(v string) *SupportTicketUpsert {
	u.Set(supportticket.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *SupportTicketUpsert) UpdateCategory() *SupportTicketUpsert {
	u.SetExcluded(supportticket.FieldCategory)
	return u
}

// SetPriority sets the "priority" field.
func (u *SupportTicketUpsert) SetPriority(v string) *SupportTicketUpsert {
	u.Set(supportticket.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SupportTicketUpsert) UpdatePriority() *SupportTicketUpsert {
	u.SetExcluded(supportticket.FieldPriority)
	return u
}

// SetStatus sets the "status" field.
func (u *SupportTicketUpsert) SetStatus(v string) *SupportTicketUpsert {
	u.Set(supportticket.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupportTicketUpsert) UpdateStatus() *SupportTicketUpsert {
	u.SetExcluded(supportticket.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupportTicketUpsert) SetUpdatedAt(v time.Time) *SupportTicketUpsert {
	u.Set(supportticket.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupportTicketUpsert) UpdateUpdatedAt() *SupportTicketUpsert {
	u.SetExcluded(supportticket.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SupportTicket.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportTicketUpsertOne) UpdateNewValues() *SupportTicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(supportticket.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportTicket.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupportTicketUpsertOne) Ignore() *SupportTicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportTicketUpsertOne) DoNothing() *SupportTicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportTicketCreate.OnConflict
// documentation for more info.
func (u *SupportTicketUpsertOne) Update(set func(*SupportTicketUpsert)) *SupportTicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportTicketUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *SupportTicketUpsertOne) SetUserID(v int64) *SupportTicketUpsertOne {
	return u.Update(func(s *SupportTicketUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SupportTicketUpsertOne) UpdateUserID() *SupportTicketUpsertOne {
	return u.Update(func(s *SupportTicketUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *SupportTicketUpsertOne) SetTitle(v string) *SupportTicketUpsertOne {
	return u.Update(func(s *SupportTicketUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SupportTicketUpsertOne) UpdateTitle() *SupportTicketUpsertOne {
	return u.Update(func(s *SupportTicketUpsert) {
		s.UpdateTitle()
	})
}

// SetCategory sets the "category" field.
func (u *SupportTicketUpsertOne) SetCategory(v string) *SupportTicketUpsertOne {
	return u.Update(func(s *SupportTicketUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *SupportTicketUpsertOne) UpdateCategory() *SupportTicketUpsertOne {
	return u.Update(func(s *SupportTicketUpsert) {
		s.UpdateCategory()
	})
}

// SetPriority sets the "priority" field.
func (u *SupportTicketUpsertOne) SetPriority(v string) *SupportTicketUpsertOne {
	return u.Update(func(s *SupportTicketUpsert) {
		s.SetPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SupportTicketUpsertOne) UpdatePriority() *SupportTicketUpsertOne {
	return u.Update(func(s *SupportTicketUpsert) {
		s.UpdatePriority()
	})
}

// SetStatus sets the "status" field.
func (u *SupportTicketUpsertOne) SetStatus(v string) *SupportTicketUpsertOne {
	return u.Update(func(s *SupportTicketUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupportTicketUpsertOne) UpdateStatus() *SupportTicketUpsertOne {
	return u.Update(func(s *SupportTicketUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupportTicketUpsertOne) SetUpdatedAt(v time.Time) *SupportTicketUpsertOne {
	return u.Update(func(s *SupportTicketUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupportTicketUpsertOne) UpdateUpdatedAt() *SupportTicketUpsertOne {
	return u.Update(func(s *SupportTicketUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SupportTicketUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportTicketCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportTicketUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupportTicketUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupportTicketUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupportTicketCreateBulk is the builder for creating many SupportTicket entities in bulk.
type SupportTicketCreateBulk struct {
	config
	err      error
	builders []*SupportTicketCreate
	conflict []sql.ConflictOption
}

// Save creates the SupportTicket entities in the database.
func (_c *SupportTicketCreateBulk) Save(ctx context.Context) ([]*SupportTicket, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupportTicket, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupportTicketMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupportTicketCreateBulk) SaveX(ctx context.Context) []*SupportTicket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportTicketCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportTicketCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportTicket.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportTicketUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportTicketCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupportTicketUpsertBulk {
	_c.conflict = opts
	return &SupportTicketUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportTicket.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportTicketCreateBulk) OnConflictColumns(columns ...string) *SupportTicketUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportTicketUpsertBulk{
		create: _c,
	}
}

// SupportTicketUpsertBulk is the builder for "upsert"-ing
// a bulk of SupportTicket nodes.
type SupportTicketUpsertBulk struct {
	create *SupportTicketCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupportTicket.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportTicketUpsertBulk) UpdateNewValues() *SupportTicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(supportticket.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportTicket.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupportTicketUpsertBulk) Ignore() *SupportTicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportTicketUpsertBulk) DoNothing() *SupportTicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportTicketCreateBulk.OnConflict
// documentation for more info.
func (u *SupportTicketUpsertBulk) Update(set func(*SupportTicketUpsert)) *SupportTicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportTicketUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *SupportTicketUpsertBulk) SetUserID(v int64) *SupportTicketUpsertBulk {
	return u.Update(func(s *SupportTicketUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SupportTicketUpsertBulk) UpdateUserID() *SupportTicketUpsertBulk {
	return u.Update(func(s *SupportTicketUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *SupportTicketUpsertBulk) SetTitle(v string) *SupportTicketUpsertBulk {
	return u.Update(func(s *SupportTicketUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SupportTicketUpsertBulk) UpdateTitle() *SupportTicketUpsertBulk {
	return u.Update(func(s *SupportTicketUpsert) {
		s.UpdateTitle()
	})
}

// SetCategory sets the "category" field.
func (u *SupportTicketUpsertBulk) SetCategory(v string) *SupportTicketUpsertBulk {
	return u.Update(func(s *SupportTicketUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *SupportTicketUpsertBulk) UpdateCategory() *SupportTicketUpsertBulk {
	return u.Update(func(s *SupportTicketUpsert) {
		s.UpdateCategory()
	})
}

// SetPriority sets the "priority" field.
func (u *SupportTicketUpsertBulk) SetPriority(v string) *SupportTicketUpsertBulk {
	return u.Update(func(s *SupportTicketUpsert) {
		s.SetPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SupportTicketUpsertBulk) UpdatePriority() *SupportTicketUpsertBulk {
	return u.Update(func(s *SupportTicketUpsert) {
		s.UpdatePriority()
	})
}

// SetStatus sets the "status" field.
func (u *SupportTicketUpsertBulk) SetStatus(v string) *SupportTicketUpsertBulk {
	return u.Update(func(s *SupportTicketUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupportTicketUpsertBulk) UpdateStatus() *SupportTicketUpsertBulk {
	return u.Update(func(s *SupportTicketUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupportTicketUpsertBulk) SetUpdatedAt(v time.Time) *SupportTicketUpsertBulk {
	return u.Update(func(s *SupportTicketUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupportTicketUpsertBulk) UpdateUpdatedAt() *SupportTicketUpsertBulk {
	return u.Update(func(s *SupportTicketUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SupportTicketUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupportTicketCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportTicketCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportTicketUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
