// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportTicketReadUpdate is the builder for updating SupportTicketRead entities.
type SupportTicketReadUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketReadMutation
}

// Where appends a list predicates to the SupportTicketReadUpdate builder.
func (_u *SupportTicketReadUpdate) Where(ps ...predicate.SupportTicketRead) *SupportTicketReadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *SupportTicketReadUpdate) SetTicketID(v int64) *SupportTicketReadUpdate {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *SupportTicketReadUpdate) SetNillableTicketID(v *int64) *SupportTicketReadUpdate {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetReaderUserID sets the "reader_user_id" field.
func (_u *SupportTicketReadUpdate) SetReaderUserID(v int64) *SupportTicketReadUpdate {
	_u.mutation.SetReaderUserID(v)
	return _u
}

// SetNillableReaderUserID sets the "reader_user_id" field if the given value is not nil.
func (_u *SupportTicketReadUpdate) SetNillableReaderUserID(v *int64) *SupportTicketReadUpdate {
	if v != nil {
		_u.SetReaderUserID(*v)
	}
	return _u
}

// SetReaderRole sets the "reader_role" field.
func (_u *SupportTicketReadUpdate) SetReaderRole(v string) *SupportTicketReadUpdate {
	_u.mutation.SetReaderRole(v)
	return _u
}

// SetNillableReaderRole sets the "reader_role" field if the given value is not nil.
func (_u *SupportTicketReadUpdate) SetNillableReaderRole(v *string) *SupportTicketReadUpdate {
	if v != nil {
		_u.SetReaderRole(*v)
	}
	return _u
}

// SetLastReadMessageID sets the "last_read_message_id" field.
func (_u *SupportTicketReadUpdate) SetLastReadMessageID(v int64) *SupportTicketReadUpdate {
	_u.mutation.ResetLastReadMessageID()
	_u.mutation.SetLastReadMessageID(v)
	return _u
}

// SetNillableLastReadMessageID sets the "last_read_message_id" field if the given value is not nil.
func (_u *SupportTicketReadUpdate) SetNillableLastReadMessageID(v *int64) *SupportTicketReadUpdate {
	if v != nil {
		_u.SetLastReadMessageID(*v)
	}
	return _u
}

// AddLastReadMessageID adds value to the "last_read_message_id" field.
func (_u *SupportTicketReadUpdate) AddLastReadMessageID(v int64) *SupportTicketReadUpdate {
	_u.mutation.AddLastReadMessageID(v)
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *SupportTicketReadUpdate) SetReadAt(v time.Time) *SupportTicketReadUpdate {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *SupportTicketReadUpdate) SetNillableReadAt(v *time.Time) *SupportTicketReadUpdate {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketReadUpdate) SetUpdatedAt(v time.Time) *SupportTicketReadUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTicket sets the "ticket" edge to the SupportTicket entity.
func (_u *SupportTicketReadUpdate) SetTicket(v *SupportTicket) *SupportTicketReadUpdate {
	return _u.SetTicketID(v.ID)
}

// SetReaderID sets the "reader" edge to the User entity by ID.
func (_u *SupportTicketReadUpdate) SetReaderID(id int64) *SupportTicketReadUpdate {
	_u.mutation.SetReaderID(id)
	return _u
}

// SetReader sets the "reader" edge to the User entity.
func (_u *SupportTicketReadUpdate) SetReader(v *User) *SupportTicketReadUpdate {
	return _u.SetReaderID(v.ID)
}

// Mutation returns the SupportTicketReadMutation object of the builder.
func (_u *SupportTicketReadUpdate) Mutation() *SupportTicketReadMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the SupportTicket entity.
func (_u *SupportTicketReadUpdate) ClearTicket() *SupportTicketReadUpdate {
	_u.mutation.ClearTicket()
	return _u
}

// ClearReader clears the "reader" edge to the User entity.
func (_u *SupportTicketReadUpdate) ClearReader() *SupportTicketReadUpdate {
	_u.mutation.ClearReader()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketReadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketReadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketReadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketReadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketReadUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticketread.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketReadUpdate) check() error {
	if v, ok := _u.mutation.ReaderRole(); ok {
		if err := supportticketread.ReaderRoleValidator(v); err != nil {
			return &ValidationError{Name: "reader_role", err: fmt.Errorf(`ent: validator failed for field "SupportTicketRead.reader_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastReadMessageID(); ok {
		if err := supportticketread.LastReadMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "last_read_message_id", err: fmt.Errorf(`ent: validator failed for field "SupportTicketRead.last_read_message_id": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketRead.ticket"`)
	}
	if _u.mutation.ReaderCleared() && len(_u.mutation.ReaderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketRead.reader"`)
	}
	return nil
}

func (_u *SupportTicketReadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketread.Table, supportticketread.Columns, sqlgraph.NewFieldSpec(supportticketread.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReaderRole(); ok {
		_spec.SetField(supportticketread.FieldReaderRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastReadMessageID(); ok {
		_spec.SetField(supportticketread.FieldLastReadMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastReadMessageID(); ok {
		_spec.AddField(supportticketread.FieldLastReadMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(supportticketread.FieldReadAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticketread.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketread.TicketTable,
			Columns: []string{supportticketread.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketread.TicketTable,
			Columns: []string{supportticketread.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketread.ReaderTable,
			Columns: []string{supportticketread.ReaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketread.ReaderTable,
			Columns: []string{supportticketread.ReaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketReadUpdateOne is the builder for updating a single SupportTicketRead entity.
type SupportTicketReadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketReadMutation
}

// SetTicketID sets the "ticket_id" field.
func (_u *SupportTicketReadUpdateOne) SetTicketID(v int64) *SupportTicketReadUpdateOne {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *SupportTicketReadUpdateOne) SetNillableTicketID(v *int64) *SupportTicketReadUpdateOne {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetReaderUserID sets the "reader_user_id" field.
func (_u *SupportTicketReadUpdateOne) SetReaderUserID(v int64) *SupportTicketReadUpdateOne {
	_u.mutation.SetReaderUserID(v)
	return _u
}

// SetNillableReaderUserID sets the "reader_user_id" field if the given value is not nil.
func (_u *SupportTicketReadUpdateOne) SetNillableReaderUserID(v *int64) *SupportTicketReadUpdateOne {
	if v != nil {
		_u.SetReaderUserID(*v)
	}
	return _u
}

// SetReaderRole sets the "reader_role" field.
func (_u *SupportTicketReadUpdateOne) SetReaderRole(v string) *SupportTicketReadUpdateOne {
	_u.mutation.SetReaderRole(v)
	return _u
}

// SetNillableReaderRole sets the "reader_role" field if the given value is not nil.
func (_u *SupportTicketReadUpdateOne) SetNillableReaderRole(v *string) *SupportTicketReadUpdateOne {
	if v != nil {
		_u.SetReaderRole(*v)
	}
	return _u
}

// SetLastReadMessageID sets the "last_read_message_id" field.
func (_u *SupportTicketReadUpdateOne) SetLastReadMessageID(v int64) *SupportTicketReadUpdateOne {
	_u.mutation.ResetLastReadMessageID()
	_u.mutation.SetLastReadMessageID(v)
	return _u
}

// SetNillableLastReadMessageID sets the "last_read_message_id" field if the given value is not nil.
func (_u *SupportTicketReadUpdateOne) SetNillableLastReadMessageID(v *int64) *SupportTicketReadUpdateOne {
	if v != nil {
		_u.SetLastReadMessageID(*v)
	}
	return _u
}

// AddLastReadMessageID adds value to the "last_read_message_id" field.
func (_u *SupportTicketReadUpdateOne) AddLastReadMessageID(v int64) *SupportTicketReadUpdateOne {
	_u.mutation.AddLastReadMessageID(v)
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *SupportTicketReadUpdateOne) SetReadAt(v time.Time) *SupportTicketReadUpdateOne {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *SupportTicketReadUpdateOne) SetNillableReadAt(v *time.Time) *SupportTicketReadUpdateOne {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketReadUpdateOne) SetUpdatedAt(v time.Time) *SupportTicketReadUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTicket sets the "ticket" edge to the SupportTicket entity.
func (_u *SupportTicketReadUpdateOne) SetTicket(v *SupportTicket) *SupportTicketReadUpdateOne {
	return _u.SetTicketID(v.ID)
}

// SetReaderID sets the "reader" edge to the User entity by ID.
func (_u *SupportTicketReadUpdateOne) SetReaderID(id int64) *SupportTicketReadUpdateOne {
	_u.mutation.SetReaderID(id)
	return _u
}

// SetReader sets the "reader" edge to the User entity.
func (_u *SupportTicketReadUpdateOne) SetReader(v *User) *SupportTicketReadUpdateOne {
	return _u.SetReaderID(v.ID)
}

// Mutation returns the SupportTicketReadMutation object of the builder.
func (_u *SupportTicketReadUpdateOne) Mutation() *SupportTicketReadMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the SupportTicket entity.
func (_u *SupportTicketReadUpdateOne) ClearTicket() *SupportTicketReadUpdateOne {
	_u.mutation.ClearTicket()
	return _u
}

// ClearReader clears the "reader" edge to the User entity.
func (_u *SupportTicketReadUpdateOne) ClearReader() *SupportTicketReadUpdateOne {
	_u.mutation.ClearReader()
	return _u
}

// Where appends a list predicates to the SupportTicketReadUpdate builder.
func (_u *SupportTicketReadUpdateOne) Where(ps ...predicate.SupportTicketRead) *SupportTicketReadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketReadUpdateOne) Select(field string, fields ...string) *SupportTicketReadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicketRead entity.
func (_u *SupportTicketReadUpdateOne) Save(ctx context.Context) (*SupportTicketRead, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketReadUpdateOne) SaveX(ctx context.Context) *SupportTicketRead {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketReadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketReadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketReadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticketread.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketReadUpdateOne) check() error {
	if v, ok := _u.mutation.ReaderRole(); ok {
		if err := supportticketread.ReaderRoleValidator(v); err != nil {
			return &ValidationError{Name: "reader_role", err: fmt.Errorf(`ent: validator failed for field "SupportTicketRead.reader_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastReadMessageID(); ok {
		if err := supportticketread.LastReadMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "last_read_message_id", err: fmt.Errorf(`ent: validator failed for field "SupportTicketRead.last_read_message_id": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketRead.ticket"`)
	}
	if _u.mutation.ReaderCleared() && len(_u.mutation.ReaderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketRead.reader"`)
	}
	return nil
}

func (_u *SupportTicketReadUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicketRead, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketread.Table, supportticketread.Columns, sqlgraph.NewFieldSpec(supportticketread.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicketRead.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticketread.FieldID)
		for _, f := range fields {
			if !supportticketread.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticketread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReaderRole(); ok {
		_spec.SetField(supportticketread.FieldReaderRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastReadMessageID(); ok {
		_spec.SetField(supportticketread.FieldLastReadMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastReadMessageID(); ok {
		_spec.AddField(supportticketread.FieldLastReadMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(supportticketread.FieldReadAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticketread.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketread.TicketTable,
			Columns: []string{supportticketread.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketread.TicketTable,
			Columns: []string{supportticketread.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketread.ReaderTable,
			Columns: []string{supportticketread.ReaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketread.ReaderTable,
			Columns: []string{supportticketread.ReaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportTicketRead{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
