// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
)

// SupportTicketAttachmentUpdate is the builder for updating SupportTicketAttachment entities.
type SupportTicketAttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketAttachmentMutation
}

// Where appends a list predicates to the SupportTicketAttachmentUpdate builder.
func (_u *SupportTicketAttachmentUpdate) Where(ps ...predicate.SupportTicketAttachment) *SupportTicketAttachmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *SupportTicketAttachmentUpdate) SetMessageID(v int64) *SupportTicketAttachmentUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableMessageID(v *int64) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *SupportTicketAttachmentUpdate) SetData(v []byte) *SupportTicketAttachmentUpdate {
	_u.mutation.SetData(v)
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *SupportTicketAttachmentUpdate) SetContentType(v string) *SupportTicketAttachmentUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableContentType(v *string) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *SupportTicketAttachmentUpdate) SetSizeBytes(v int64) *SupportTicketAttachmentUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableSizeBytes(v *int64) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *SupportTicketAttachmentUpdate) AddSizeBytes(v int64) *SupportTicketAttachmentUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *SupportTicketAttachmentUpdate) SetWidth(v int) *SupportTicketAttachmentUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableWidth(v *int) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *SupportTicketAttachmentUpdate) AddWidth(v int) *SupportTicketAttachmentUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *SupportTicketAttachmentUpdate) ClearWidth() *SupportTicketAttachmentUpdate {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *SupportTicketAttachmentUpdate) SetHeight(v int) *SupportTicketAttachmentUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdate) SetNillableHeight(v *int) *SupportTicketAttachmentUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *SupportTicketAttachmentUpdate) AddHeight(v int) *SupportTicketAttachmentUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *SupportTicketAttachmentUpdate) ClearHeight() *SupportTicketAttachmentUpdate {
	_u.mutation.ClearHeight()
	return _u
}

// SetMessage sets the "message" edge to the SupportTicketMessage entity.
func (_u *SupportTicketAttachmentUpdate) SetMessage(v *SupportTicketMessage) *SupportTicketAttachmentUpdate {
	return _u.SetMessageID(v.ID)
}

// Mutation returns the SupportTicketAttachmentMutation object of the builder.
func (_u *SupportTicketAttachmentUpdate) Mutation() *SupportTicketAttachmentMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the SupportTicketMessage entity.
func (_u *SupportTicketAttachmentUpdate) ClearMessage() *SupportTicketAttachmentUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketAttachmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketAttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketAttachmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketAttachmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketAttachmentUpdate) check() error {
	if v, ok := _u.mutation.ContentType(); ok {
		if err := supportticketattachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := supportticketattachment.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.size_bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Width(); ok {
		if err := supportticketattachment.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := supportticketattachment.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.height": %w`, err)}
		}
	}
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketAttachment.message"`)
	}
	return nil
}

func (_u *SupportTicketAttachmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketattachment.Table, supportticketattachment.Columns, sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(supportticketattachment.FieldData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(supportticketattachment.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(supportticketattachment.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(supportticketattachment.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(supportticketattachment.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(supportticketattachment.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(supportticketattachment.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(supportticketattachment.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(supportticketattachment.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(supportticketattachment.FieldHeight, field.TypeInt)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.MessageTable,
			Columns: []string{supportticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.MessageTable,
			Columns: []string{supportticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketAttachmentUpdateOne is the builder for updating a single SupportTicketAttachment entity.
type SupportTicketAttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketAttachmentMutation
}

// SetMessageID sets the "message_id" field.
func (_u *SupportTicketAttachmentUpdateOne) SetMessageID(v int64) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableMessageID(v *int64) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *SupportTicketAttachmentUpdateOne) SetData(v []byte) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *SupportTicketAttachmentUpdateOne) SetContentType(v string) *SupportTicketAttachmentUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableContentType(v *string) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *SupportTicketAttachmentUpdateOne) SetSizeBytes(v int64) *SupportTicketAttachmentUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableSizeBytes(v *int64) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *SupportTicketAttachmentUpdateOne) AddSizeBytes(v int64) *SupportTicketAttachmentUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *SupportTicketAttachmentUpdateOne) SetWidth(v int) *SupportTicketAttachmentUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableWidth(v *int) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *SupportTicketAttachmentUpdateOne) AddWidth(v int) *SupportTicketAttachmentUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *SupportTicketAttachmentUpdateOne) ClearWidth() *SupportTicketAttachmentUpdateOne {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *SupportTicketAttachmentUpdateOne) SetHeight(v int) *SupportTicketAttachmentUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *SupportTicketAttachmentUpdateOne) SetNillableHeight(v *int) *SupportTicketAttachmentUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *SupportTicketAttachmentUpdateOne) AddHeight(v int) *SupportTicketAttachmentUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *SupportTicketAttachmentUpdateOne) ClearHeight() *SupportTicketAttachmentUpdateOne {
	_u.mutation.ClearHeight()
	return _u
}

// SetMessage sets the "message" edge to the SupportTicketMessage entity.
func (_u *SupportTicketAttachmentUpdateOne) SetMessage(v *SupportTicketMessage) *SupportTicketAttachmentUpdateOne {
	return _u.SetMessageID(v.ID)
}

// Mutation returns the SupportTicketAttachmentMutation object of the builder.
func (_u *SupportTicketAttachmentUpdateOne) Mutation() *SupportTicketAttachmentMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the SupportTicketMessage entity.
func (_u *SupportTicketAttachmentUpdateOne) ClearMessage() *SupportTicketAttachmentUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// Where appends a list predicates to the SupportTicketAttachmentUpdate builder.
func (_u *SupportTicketAttachmentUpdateOne) Where(ps ...predicate.SupportTicketAttachment) *SupportTicketAttachmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketAttachmentUpdateOne) Select(field string, fields ...string) *SupportTicketAttachmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicketAttachment entity.
func (_u *SupportTicketAttachmentUpdateOne) Save(ctx context.Context) (*SupportTicketAttachment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketAttachmentUpdateOne) SaveX(ctx context.Context) *SupportTicketAttachment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketAttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketAttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketAttachmentUpdateOne) check() error {
	if v, ok := _u.mutation.ContentType(); ok {
		if err := supportticketattachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := supportticketattachment.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.size_bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Width(); ok {
		if err := supportticketattachment.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := supportticketattachment.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "SupportTicketAttachment.height": %w`, err)}
		}
	}
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketAttachment.message"`)
	}
	return nil
}

func (_u *SupportTicketAttachmentUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicketAttachment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketattachment.Table, supportticketattachment.Columns, sqlgraph.NewFieldSpec(supportticketattachment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicketAttachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticketattachment.FieldID)
		for _, f := range fields {
			if !supportticketattachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticketattachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(supportticketattachment.FieldData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(supportticketattachment.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(supportticketattachment.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(supportticketattachment.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(supportticketattachment.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(supportticketattachment.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(supportticketattachment.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(supportticketattachment.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(supportticketattachment.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(supportticketattachment.FieldHeight, field.TypeInt)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.MessageTable,
			Columns: []string{supportticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketattachment.MessageTable,
			Columns: []string{supportticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportTicketAttachment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
