// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportTicketMessage is the model entity for the SupportTicketMessage schema.
type SupportTicketMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TicketID holds the value of the "ticket_id" field.
	TicketID int64 `json:"ticket_id,omitempty"`
	// AuthorUserID holds the value of the "author_user_id" field.
	AuthorUserID int64 `json:"author_user_id,omitempty"`
	// AuthorRole holds the value of the "author_role" field.
	AuthorRole string `json:"author_role,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupportTicketMessageQuery when eager-loading is set.
	Edges        SupportTicketMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SupportTicketMessageEdges holds the relations/edges for other nodes in the graph.
type SupportTicketMessageEdges struct {
	// Ticket holds the value of the ticket edge.
	Ticket *SupportTicket `json:"ticket,omitempty"`
	// Author holds the value of the author edge.
	Author *User `json:"author,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*SupportTicketAttachment `json:"attachments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TicketOrErr returns the Ticket value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportTicketMessageEdges) TicketOrErr() (*SupportTicket, error) {
	if e.Ticket != nil {
		return e.Ticket, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: supportticket.Label}
	}
	return nil, &NotLoadedError{edge: "ticket"}
}

// AuthorOrErr returns the Author value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportTicketMessageEdges) AuthorOrErr() (*User, error) {
	if e.Author != nil {
		return e.Author, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "author"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e SupportTicketMessageEdges) AttachmentsOrErr() ([]*SupportTicketAttachment, error) {
	if e.loadedTypes[2] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupportTicketMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supportticketmessage.FieldID, supportticketmessage.FieldTicketID, supportticketmessage.FieldAuthorUserID:
			values[i] = new(sql.NullInt64)
		case supportticketmessage.FieldAuthorRole, supportticketmessage.FieldBody:
			values[i] = new(sql.NullString)
		case supportticketmessage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupportTicketMessage fields.
func (_m *SupportTicketMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supportticketmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case supportticketmessage.FieldTicketID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_id", values[i])
			} else if value.Valid {
				_m.TicketID = value.Int64
			}
		case supportticketmessage.FieldAuthorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field author_user_id", values[i])
			} else if value.Valid {
				_m.AuthorUserID = value.Int64
			}
		case supportticketmessage.FieldAuthorRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author_role", values[i])
			} else if value.Valid {
				_m.AuthorRole = value.String
			}
		case supportticketmessage.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case supportticketmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupportTicketMessage.
// This includes values selected through modifiers, order, etc.
func (_m *SupportTicketMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTicket queries the "ticket" edge of the SupportTicketMessage entity.
func (_m *SupportTicketMessage) QueryTicket() *SupportTicketQuery {
	return NewSupportTicketMessageClient(_m.config).QueryTicket(_m)
}

// QueryAuthor queries the "author" edge of the SupportTicketMessage entity.
func (_m *SupportTicketMessage) QueryAuthor() *UserQuery {
	return NewSupportTicketMessageClient(_m.config).QueryAuthor(_m)
}

// QueryAttachments queries the "attachments" edge of the SupportTicketMessage entity.
func (_m *SupportTicketMessage) QueryAttachments() *SupportTicketAttachmentQuery {
	return NewSupportTicketMessageClient(_m.config).QueryAttachments(_m)
}

// Update returns a builder for updating this SupportTicketMessage.
// Note that you need to call SupportTicketMessage.Unwrap() before calling this method if this SupportTicketMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupportTicketMessage) Update() *SupportTicketMessageUpdateOne {
	return NewSupportTicketMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupportTicketMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupportTicketMessage) Unwrap() *SupportTicketMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupportTicketMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupportTicketMessage) String() string {
	var builder strings.Builder
	builder.WriteString("SupportTicketMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ticket_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TicketID))
	builder.WriteString(", ")
	builder.WriteString("author_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthorUserID))
	builder.WriteString(", ")
	builder.WriteString("author_role=")
	builder.WriteString(_m.AuthorRole)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupportTicketMessages is a parsable slice of SupportTicketMessage.
type SupportTicketMessages []*SupportTicketMessage
