// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportTicketReadCreate is the builder for creating a SupportTicketRead entity.
type SupportTicketReadCreate struct {
	config
	mutation *SupportTicketReadMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTicketID sets the "ticket_id" field.
func (_c *SupportTicketReadCreate) SetTicketID(v int64) *SupportTicketReadCreate {
	_c.mutation.SetTicketID(v)
	return _c
}

// SetReaderUserID sets the "reader_user_id" field.
func (_c *SupportTicketReadCreate) SetReaderUserID(v int64) *SupportTicketReadCreate {
	_c.mutation.SetReaderUserID(v)
	return _c
}

// SetReaderRole sets the "reader_role" field.
func (_c *SupportTicketReadCreate) SetReaderRole(v string) *SupportTicketReadCreate {
	_c.mutation.SetReaderRole(v)
	return _c
}

// SetLastReadMessageID sets the "last_read_message_id" field.
func (_c *SupportTicketReadCreate) SetLastReadMessageID(v int64) *SupportTicketReadCreate {
	_c.mutation.SetLastReadMessageID(v)
	return _c
}

// SetNillableLastReadMessageID sets the "last_read_message_id" field if the given value is not nil.
func (_c *SupportTicketReadCreate) SetNillableLastReadMessageID(v *int64) *SupportTicketReadCreate {
	if v != nil {
		_c.SetLastReadMessageID(*v)
	}
	return _c
}

// SetReadAt sets the "read_at" field.
func (_c *SupportTicketReadCreate) SetReadAt(v time.Time) *SupportTicketReadCreate {
	_c.mutation.SetReadAt(v)
	return _c
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_c *SupportTicketReadCreate) SetNillableReadAt(v *time.Time) *SupportTicketReadCreate {
	if v != nil {
		_c.SetReadAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupportTicketReadCreate) SetCreatedAt(v time.Time) *SupportTicketReadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupportTicketReadCreate) SetNillableCreatedAt(v *time.Time) *SupportTicketReadCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SupportTicketReadCreate) SetUpdatedAt(v time.Time) *SupportTicketReadCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SupportTicketReadCreate) SetNillableUpdatedAt(v *time.Time) *SupportTicketReadCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTicket sets the "ticket" edge to the SupportTicket entity.
func (_c *SupportTicketReadCreate) SetTicket(v *SupportTicket) *SupportTicketReadCreate {
	return _c.SetTicketID(v.ID)
}

// SetReaderID sets the "reader" edge to the User entity by ID.
func (_c *SupportTicketReadCreate) SetReaderID(id int64) *SupportTicketReadCreate {
	_c.mutation.SetReaderID(id)
	return _c
}

// SetReader sets the "reader" edge to the User entity.
func (_c *SupportTicketReadCreate) SetReader(v *User) *SupportTicketReadCreate {
	return _c.SetReaderID(v.ID)
}

// Mutation returns the SupportTicketReadMutation object of the builder.
func (_c *SupportTicketReadCreate) Mutation() *SupportTicketReadMutation {
	return _c.mutation
}

// Save creates the SupportTicketRead in the database.
func (_c *SupportTicketReadCreate) Save(ctx context.Context) (*SupportTicketRead, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupportTicketReadCreate) SaveX(ctx context.Context) *SupportTicketRead {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportTicketReadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportTicketReadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupportTicketReadCreate) defaults() {
	if _, ok := _c.mutation.LastReadMessageID(); !ok {
		v := supportticketread.DefaultLastReadMessageID
		_c.mutation.SetLastReadMessageID(v)
	}
	if _, ok := _c.mutation.ReadAt(); !ok {
		v := supportticketread.DefaultReadAt()
		_c.mutation.SetReadAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := supportticketread.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := supportticketread.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupportTicketReadCreate) check() error {
	if _, ok := _c.mutation.TicketID(); !ok {
		return &ValidationError{Name: "ticket_id", err: errors.New(`ent: missing required field "SupportTicketRead.ticket_id"`)}
	}
	if _, ok := _c.mutation.ReaderUserID(); !ok {
		return &ValidationError{Name: "reader_user_id", err: errors.New(`ent: missing required field "SupportTicketRead.reader_user_id"`)}
	}
	if _, ok := _c.mutation.ReaderRole(); !ok {
		return &ValidationError{Name: "reader_role", err: errors.New(`ent: missing required field "SupportTicketRead.reader_role"`)}
	}
	if v, ok := _c.mutation.ReaderRole(); ok {
		if err := supportticketread.ReaderRoleValidator(v); err != nil {
			return &ValidationError{Name: "reader_role", err: fmt.Errorf(`ent: validator failed for field "SupportTicketRead.reader_role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastReadMessageID(); !ok {
		return &ValidationError{Name: "last_read_message_id", err: errors.New(`ent: missing required field "SupportTicketRead.last_read_message_id"`)}
	}
	if v, ok := _c.mutation.LastReadMessageID(); ok {
		if err := supportticketread.LastReadMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "last_read_message_id", err: fmt.Errorf(`ent: validator failed for field "SupportTicketRead.last_read_message_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReadAt(); !ok {
		return &ValidationError{Name: "read_at", err: errors.New(`ent: missing required field "SupportTicketRead.read_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupportTicketRead.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SupportTicketRead.updated_at"`)}
	}
	if len(_c.mutation.TicketIDs()) == 0 {
		return &ValidationError{Name: "ticket", err: errors.New(`ent: missing required edge "SupportTicketRead.ticket"`)}
	}
	if len(_c.mutation.ReaderIDs()) == 0 {
		return &ValidationError{Name: "reader", err: errors.New(`ent: missing required edge "SupportTicketRead.reader"`)}
	}
	return nil
}

func (_c *SupportTicketReadCreate) sqlSave(ctx context.Context) (*SupportTicketRead, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupportTicketReadCreate) createSpec() (*SupportTicketRead, *sqlgraph.CreateSpec) {
	var (
		_node = &SupportTicketRead{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supportticketread.Table, sqlgraph.NewFieldSpec(supportticketread.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ReaderRole(); ok {
		_spec.SetField(supportticketread.FieldReaderRole, field.TypeString, value)
		_node.ReaderRole = value
	}
	if value, ok := _c.mutation.LastReadMessageID(); ok {
		_spec.SetField(supportticketread.FieldLastReadMessageID, field.TypeInt64, value)
		_node.LastReadMessageID = value
	}
	if value, ok := _c.mutation.ReadAt(); ok {
		_spec.SetField(supportticketread.FieldReadAt, field.TypeTime, value)
		_node.ReadAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supportticketread.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticketread.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketread.TicketTable,
			Columns: []string{supportticketread.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TicketID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketread.ReaderTable,
			Columns: []string{supportticketread.ReaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReaderUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportTicketRead.Create().
//		SetTicketID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportTicketReadUpsert) {
//			SetTicketID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportTicketReadCreate) OnConflict(opts ...sql.ConflictOption) *SupportTicketReadUpsertOne {
	_c.conflict = opts
	return &SupportTicketReadUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportTicketRead.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportTicketReadCreate) OnConflictColumns(columns ...string) *SupportTicketReadUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportTicketReadUpsertOne{
		create: _c,
	}
}

type (
	// SupportTicketReadUpsertOne is the builder for "upsert"-ing
	//  one SupportTicketRead node.
	SupportTicketReadUpsertOne struct {
		create *SupportTicketReadCreate
	}

	// SupportTicketReadUpsert is the "OnConflict" setter.
	SupportTicketReadUpsert struct {
		*sql.UpdateSet
	}
)

// SetTicketID sets the "ticket_id" field.
func (u *SupportTicketReadUpsert) SetTicketID(v int64) *SupportTicketReadUpsert {
	u.Set(supportticketread.FieldTicketID, v)
	return u
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *SupportTicketReadUpsert) UpdateTicketID() *SupportTicketReadUpsert {
	u.SetExcluded(supportticketread.FieldTicketID)
	return u
}

// SetReaderUserID sets the "reader_user_id" field.
func (u *SupportTicketReadUpsert) SetReaderUserID(v int64) *SupportTicketReadUpsert {
	u.Set(supportticketread.FieldReaderUserID, v)
	return u
}

// UpdateReaderUserID sets the "reader_user_id" field to the value that was provided on create.
func (u *SupportTicketReadUpsert) UpdateReaderUserID() *SupportTicketReadUpsert {
	u.SetExcluded(supportticketread.FieldReaderUserID)
	return u
}

// SetReaderRole sets the "reader_role" field.
func (u *SupportTicketReadUpsert) SetReaderRole(v string) *SupportTicketReadUpsert {
	u.Set(supportticketread.FieldReaderRole, v)
	return u
}

// UpdateReaderRole sets the "reader_role" field to the value that was provided on create.
func (u *SupportTicketReadUpsert) UpdateReaderRole() *SupportTicketReadUpsert {
	u.SetExcluded(supportticketread.FieldReaderRole)
	return u
}

// SetLastReadMessageID sets the "last_read_message_id" field.
func (u *SupportTicketReadUpsert) SetLastReadMessageID(v int64) *SupportTicketReadUpsert {
	u.Set(supportticketread.FieldLastReadMessageID, v)
	return u
}

// UpdateLastReadMessageID sets the "last_read_message_id" field to the value that was provided on create.
func (u *SupportTicketReadUpsert) UpdateLastReadMessageID() *SupportTicketReadUpsert {
	u.SetExcluded(supportticketread.FieldLastReadMessageID)
	return u
}

// AddLastReadMessageID adds v to the "last_read_message_id" field.
func (u *SupportTicketReadUpsert) AddLastReadMessageID(v int64) *SupportTicketReadUpsert {
	u.Add(supportticketread.FieldLastReadMessageID, v)
	return u
}

// SetReadAt sets the "read_at" field.
func (u *SupportTicketReadUpsert) SetReadAt(v time.Time) *SupportTicketReadUpsert {
	u.Set(supportticketread.FieldReadAt, v)
	return u
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *SupportTicketReadUpsert) UpdateReadAt() *SupportTicketReadUpsert {
	u.SetExcluded(supportticketread.FieldReadAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupportTicketReadUpsert) SetUpdatedAt(v time.Time) *SupportTicketReadUpsert {
	u.Set(supportticketread.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupportTicketReadUpsert) UpdateUpdatedAt() *SupportTicketReadUpsert {
	u.SetExcluded(supportticketread.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SupportTicketRead.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportTicketReadUpsertOne) UpdateNewValues() *SupportTicketReadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(supportticketread.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportTicketRead.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupportTicketReadUpsertOne) Ignore() *SupportTicketReadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportTicketReadUpsertOne) DoNothing() *SupportTicketReadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportTicketReadCreate.OnConflict
// documentation for more info.
func (u *SupportTicketReadUpsertOne) Update(set func(*SupportTicketReadUpsert)) *SupportTicketReadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportTicketReadUpsert{UpdateSet: update})
	}))
	return u
}

// SetTicketID sets the "ticket_id" field.
func (u *SupportTicketReadUpsertOne) SetTicketID(v int64) *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.SetTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *SupportTicketReadUpsertOne) UpdateTicketID() *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.UpdateTicketID()
	})
}

// SetReaderUserID sets the "reader_user_id" field.
func (u *SupportTicketReadUpsertOne) SetReaderUserID(v int64) *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.SetReaderUserID(v)
	})
}

// UpdateReaderUserID sets the "reader_user_id" field to the value that was provided on create.
func (u *SupportTicketReadUpsertOne) UpdateReaderUserID() *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.UpdateReaderUserID()
	})
}

// SetReaderRole sets the "reader_role" field.
func (u *SupportTicketReadUpsertOne) SetReaderRole(v string) *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.SetReaderRole(v)
	})
}

// UpdateReaderRole sets the "reader_role" field to the value that was provided on create.
func (u *SupportTicketReadUpsertOne) UpdateReaderRole() *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.UpdateReaderRole()
	})
}

// SetLastReadMessageID sets the "last_read_message_id" field.
func (u *SupportTicketReadUpsertOne) SetLastReadMessageID(v int64) *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.SetLastReadMessageID(v)
	})
}

// AddLastReadMessageID adds v to the "last_read_message_id" field.
func (u *SupportTicketReadUpsertOne) AddLastReadMessageID(v int64) *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.AddLastReadMessageID(v)
	})
}

// UpdateLastReadMessageID sets the "last_read_message_id" field to the value that was provided on create.
func (u *SupportTicketReadUpsertOne) UpdateLastReadMessageID() *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.UpdateLastReadMessageID()
	})
}

// SetReadAt sets the "read_at" field.
func (u *SupportTicketReadUpsertOne) SetReadAt(v time.Time) *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.SetReadAt(v)
	})
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *SupportTicketReadUpsertOne) UpdateReadAt() *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.UpdateReadAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupportTicketReadUpsertOne) SetUpdatedAt(v time.Time) *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupportTicketReadUpsertOne) UpdateUpdatedAt() *SupportTicketReadUpsertOne {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SupportTicketReadUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportTicketReadCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportTicketReadUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupportTicketReadUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupportTicketReadUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupportTicketReadCreateBulk is the builder for creating many SupportTicketRead entities in bulk.
type SupportTicketReadCreateBulk struct {
	config
	err      error
	builders []*SupportTicketReadCreate
	conflict []sql.ConflictOption
}

// Save creates the SupportTicketRead entities in the database.
func (_c *SupportTicketReadCreateBulk) Save(ctx context.Context) ([]*SupportTicketRead, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupportTicketRead, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupportTicketReadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupportTicketReadCreateBulk) SaveX(ctx context.Context) []*SupportTicketRead {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportTicketReadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportTicketReadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportTicketRead.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportTicketReadUpsert) {
//			SetTicketID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportTicketReadCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupportTicketReadUpsertBulk {
	_c.conflict = opts
	return &SupportTicketReadUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportTicketRead.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportTicketReadCreateBulk) OnConflictColumns(columns ...string) *SupportTicketReadUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportTicketReadUpsertBulk{
		create: _c,
	}
}

// SupportTicketReadUpsertBulk is the builder for "upsert"-ing
// a bulk of SupportTicketRead nodes.
type SupportTicketReadUpsertBulk struct {
	create *SupportTicketReadCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupportTicketRead.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportTicketReadUpsertBulk) UpdateNewValues() *SupportTicketReadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(supportticketread.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportTicketRead.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupportTicketReadUpsertBulk) Ignore() *SupportTicketReadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportTicketReadUpsertBulk) DoNothing() *SupportTicketReadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportTicketReadCreateBulk.OnConflict
// documentation for more info.
func (u *SupportTicketReadUpsertBulk) Update(set func(*SupportTicketReadUpsert)) *SupportTicketReadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportTicketReadUpsert{UpdateSet: update})
	}))
	return u
}

// SetTicketID sets the "ticket_id" field.
func (u *SupportTicketReadUpsertBulk) SetTicketID(v int64) *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.SetTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *SupportTicketReadUpsertBulk) UpdateTicketID() *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.UpdateTicketID()
	})
}

// SetReaderUserID sets the "reader_user_id" field.
func (u *SupportTicketReadUpsertBulk) SetReaderUserID(v int64) *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.SetReaderUserID(v)
	})
}

// UpdateReaderUserID sets the "reader_user_id" field to the value that was provided on create.
func (u *SupportTicketReadUpsertBulk) UpdateReaderUserID() *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.UpdateReaderUserID()
	})
}

// SetReaderRole sets the "reader_role" field.
func (u *SupportTicketReadUpsertBulk) SetReaderRole(v string) *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.SetReaderRole(v)
	})
}

// UpdateReaderRole sets the "reader_role" field to the value that was provided on create.
func (u *SupportTicketReadUpsertBulk) UpdateReaderRole() *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.UpdateReaderRole()
	})
}

// SetLastReadMessageID sets the "last_read_message_id" field.
func (u *SupportTicketReadUpsertBulk) SetLastReadMessageID(v int64) *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.SetLastReadMessageID(v)
	})
}

// AddLastReadMessageID adds v to the "last_read_message_id" field.
func (u *SupportTicketReadUpsertBulk) AddLastReadMessageID(v int64) *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.AddLastReadMessageID(v)
	})
}

// UpdateLastReadMessageID sets the "last_read_message_id" field to the value that was provided on create.
func (u *SupportTicketReadUpsertBulk) UpdateLastReadMessageID() *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.UpdateLastReadMessageID()
	})
}

// SetReadAt sets the "read_at" field.
func (u *SupportTicketReadUpsertBulk) SetReadAt(v time.Time) *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.SetReadAt(v)
	})
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *SupportTicketReadUpsertBulk) UpdateReadAt() *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.UpdateReadAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupportTicketReadUpsertBulk) SetUpdatedAt(v time.Time) *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupportTicketReadUpsertBulk) UpdateUpdatedAt() *SupportTicketReadUpsertBulk {
	return u.Update(func(s *SupportTicketReadUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SupportTicketReadUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupportTicketReadCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportTicketReadCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportTicketReadUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
