// Code generated by ent, DO NOT EDIT.

package supportticketread

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the supportticketread type in the database.
	Label = "support_ticket_read"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTicketID holds the string denoting the ticket_id field in the database.
	FieldTicketID = "ticket_id"
	// FieldReaderUserID holds the string denoting the reader_user_id field in the database.
	FieldReaderUserID = "reader_user_id"
	// FieldReaderRole holds the string denoting the reader_role field in the database.
	FieldReaderRole = "reader_role"
	// FieldLastReadMessageID holds the string denoting the last_read_message_id field in the database.
	FieldLastReadMessageID = "last_read_message_id"
	// FieldReadAt holds the string denoting the read_at field in the database.
	FieldReadAt = "read_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTicket holds the string denoting the ticket edge name in mutations.
	EdgeTicket = "ticket"
	// EdgeReader holds the string denoting the reader edge name in mutations.
	EdgeReader = "reader"
	// Table holds the table name of the supportticketread in the database.
	Table = "support_ticket_reads"
	// TicketTable is the table that holds the ticket relation/edge.
	TicketTable = "support_ticket_reads"
	// TicketInverseTable is the table name for the SupportTicket entity.
	// It exists in this package in order to avoid circular dependency with the "supportticket" package.
	TicketInverseTable = "support_tickets"
	// TicketColumn is the table column denoting the ticket relation/edge.
	TicketColumn = "ticket_id"
	// ReaderTable is the table that holds the reader relation/edge.
	ReaderTable = "support_ticket_reads"
	// ReaderInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReaderInverseTable = "users"
	// ReaderColumn is the table column denoting the reader relation/edge.
	ReaderColumn = "reader_user_id"
)

// Columns holds all SQL columns for supportticketread fields.
var Columns = []string{
	FieldID,
	FieldTicketID,
	FieldReaderUserID,
	FieldReaderRole,
	FieldLastReadMessageID,
	FieldReadAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ReaderRoleValidator is a validator for the "reader_role" field. It is called by the builders before save.
	ReaderRoleValidator func(string) error
	// DefaultLastReadMessageID holds the default value on creation for the "last_read_message_id" field.
	DefaultLastReadMessageID int64
	// LastReadMessageIDValidator is a validator for the "last_read_message_id" field. It is called by the builders before save.
	LastReadMessageIDValidator func(int64) error
	// DefaultReadAt holds the default value on creation for the "read_at" field.
	DefaultReadAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the SupportTicketRead queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTicketID orders the results by the ticket_id field.
func ByTicketID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketID, opts...).ToFunc()
}

// ByReaderUserID orders the results by the reader_user_id field.
func ByReaderUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReaderUserID, opts...).ToFunc()
}

// ByReaderRole orders the results by the reader_role field.
func ByReaderRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReaderRole, opts...).ToFunc()
}

// ByLastReadMessageID orders the results by the last_read_message_id field.
func ByLastReadMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastReadMessageID, opts...).ToFunc()
}

// ByReadAt orders the results by the read_at field.
func ByReadAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReadAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTicketField orders the results by ticket field.
func ByTicketField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTicketStep(), sql.OrderByField(field, opts...))
	}
}

// ByReaderField orders the results by reader field.
func ByReaderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReaderStep(), sql.OrderByField(field, opts...))
	}
}
func newTicketStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TicketInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
	)
}
func newReaderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReaderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReaderTable, ReaderColumn),
	)
}
