// Code generated by ent, DO NOT EDIT.

package supportticketread

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLTE(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldTicketID, v))
}

// ReaderUserID applies equality check predicate on the "reader_user_id" field. It's identical to ReaderUserIDEQ.
func ReaderUserID(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldReaderUserID, v))
}

// ReaderRole applies equality check predicate on the "reader_role" field. It's identical to ReaderRoleEQ.
func ReaderRole(v string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldReaderRole, v))
}

// LastReadMessageID applies equality check predicate on the "last_read_message_id" field. It's identical to LastReadMessageIDEQ.
func LastReadMessageID(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldLastReadMessageID, v))
}

// ReadAt applies equality check predicate on the "read_at" field. It's identical to ReadAtEQ.
func ReadAt(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldReadAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldUpdatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldTicketID, vs...))
}

// ReaderUserIDEQ applies the EQ predicate on the "reader_user_id" field.
func ReaderUserIDEQ(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldReaderUserID, v))
}

// ReaderUserIDNEQ applies the NEQ predicate on the "reader_user_id" field.
func ReaderUserIDNEQ(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldReaderUserID, v))
}

// ReaderUserIDIn applies the In predicate on the "reader_user_id" field.
func ReaderUserIDIn(vs ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldReaderUserID, vs...))
}

// ReaderUserIDNotIn applies the NotIn predicate on the "reader_user_id" field.
func ReaderUserIDNotIn(vs ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldReaderUserID, vs...))
}

// ReaderRoleEQ applies the EQ predicate on the "reader_role" field.
func ReaderRoleEQ(v string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldReaderRole, v))
}

// ReaderRoleNEQ applies the NEQ predicate on the "reader_role" field.
func ReaderRoleNEQ(v string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldReaderRole, v))
}

// ReaderRoleIn applies the In predicate on the "reader_role" field.
func ReaderRoleIn(vs ...string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldReaderRole, vs...))
}

// ReaderRoleNotIn applies the NotIn predicate on the "reader_role" field.
func ReaderRoleNotIn(vs ...string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldReaderRole, vs...))
}

// ReaderRoleGT applies the GT predicate on the "reader_role" field.
func ReaderRoleGT(v string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGT(FieldReaderRole, v))
}

// ReaderRoleGTE applies the GTE predicate on the "reader_role" field.
func ReaderRoleGTE(v string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGTE(FieldReaderRole, v))
}

// ReaderRoleLT applies the LT predicate on the "reader_role" field.
func ReaderRoleLT(v string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLT(FieldReaderRole, v))
}

// ReaderRoleLTE applies the LTE predicate on the "reader_role" field.
func ReaderRoleLTE(v string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLTE(FieldReaderRole, v))
}

// ReaderRoleContains applies the Contains predicate on the "reader_role" field.
func ReaderRoleContains(v string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldContains(FieldReaderRole, v))
}

// ReaderRoleHasPrefix applies the HasPrefix predicate on the "reader_role" field.
func ReaderRoleHasPrefix(v string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldHasPrefix(FieldReaderRole, v))
}

// ReaderRoleHasSuffix applies the HasSuffix predicate on the "reader_role" field.
func ReaderRoleHasSuffix(v string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldHasSuffix(FieldReaderRole, v))
}

// ReaderRoleEqualFold applies the EqualFold predicate on the "reader_role" field.
func ReaderRoleEqualFold(v string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEqualFold(FieldReaderRole, v))
}

// ReaderRoleContainsFold applies the ContainsFold predicate on the "reader_role" field.
func ReaderRoleContainsFold(v string) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldContainsFold(FieldReaderRole, v))
}

// LastReadMessageIDEQ applies the EQ predicate on the "last_read_message_id" field.
func LastReadMessageIDEQ(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldLastReadMessageID, v))
}

// LastReadMessageIDNEQ applies the NEQ predicate on the "last_read_message_id" field.
func LastReadMessageIDNEQ(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldLastReadMessageID, v))
}

// LastReadMessageIDIn applies the In predicate on the "last_read_message_id" field.
func LastReadMessageIDIn(vs ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldLastReadMessageID, vs...))
}

// LastReadMessageIDNotIn applies the NotIn predicate on the "last_read_message_id" field.
func LastReadMessageIDNotIn(vs ...int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldLastReadMessageID, vs...))
}

// LastReadMessageIDGT applies the GT predicate on the "last_read_message_id" field.
func LastReadMessageIDGT(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGT(FieldLastReadMessageID, v))
}

// LastReadMessageIDGTE applies the GTE predicate on the "last_read_message_id" field.
func LastReadMessageIDGTE(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGTE(FieldLastReadMessageID, v))
}

// LastReadMessageIDLT applies the LT predicate on the "last_read_message_id" field.
func LastReadMessageIDLT(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLT(FieldLastReadMessageID, v))
}

// LastReadMessageIDLTE applies the LTE predicate on the "last_read_message_id" field.
func LastReadMessageIDLTE(v int64) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLTE(FieldLastReadMessageID, v))
}

// ReadAtEQ applies the EQ predicate on the "read_at" field.
func ReadAtEQ(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldReadAt, v))
}

// ReadAtNEQ applies the NEQ predicate on the "read_at" field.
func ReadAtNEQ(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldReadAt, v))
}

// ReadAtIn applies the In predicate on the "read_at" field.
func ReadAtIn(vs ...time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldReadAt, vs...))
}

// ReadAtNotIn applies the NotIn predicate on the "read_at" field.
func ReadAtNotIn(vs ...time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldReadAt, vs...))
}

// ReadAtGT applies the GT predicate on the "read_at" field.
func ReadAtGT(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGT(FieldReadAt, v))
}

// ReadAtGTE applies the GTE predicate on the "read_at" field.
func ReadAtGTE(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGTE(FieldReadAt, v))
}

// ReadAtLT applies the LT predicate on the "read_at" field.
func ReadAtLT(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLT(FieldReadAt, v))
}

// ReadAtLTE applies the LTE predicate on the "read_at" field.
func ReadAtLTE(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLTE(FieldReadAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.SupportTicketRead {
	return predicate.SupportTicketRead(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.SupportTicket) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(func(s *sql.Selector) {
		step := newTicketStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReader applies the HasEdge predicate on the "reader" edge.
func HasReader() predicate.SupportTicketRead {
	return predicate.SupportTicketRead(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReaderTable, ReaderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReaderWith applies the HasEdge predicate on the "reader" edge with a given conditions (other predicates).
func HasReaderWith(preds ...predicate.User) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(func(s *sql.Selector) {
		step := newReaderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportTicketRead) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportTicketRead) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportTicketRead) predicate.SupportTicketRead {
	return predicate.SupportTicketRead(sql.NotPredicates(p))
}
