// Code generated by ent, DO NOT EDIT.

package supportticketmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// AuthorUserID applies equality check predicate on the "author_user_id" field. It's identical to AuthorUserIDEQ.
func AuthorUserID(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorUserID, v))
}

// AuthorRole applies equality check predicate on the "author_role" field. It's identical to AuthorRoleEQ.
func AuthorRole(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorRole, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldBody, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldTicketID, vs...))
}

// AuthorUserIDEQ applies the EQ predicate on the "author_user_id" field.
func AuthorUserIDEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorUserID, v))
}

// AuthorUserIDNEQ applies the NEQ predicate on the "author_user_id" field.
func AuthorUserIDNEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldAuthorUserID, v))
}

// AuthorUserIDIn applies the In predicate on the "author_user_id" field.
func AuthorUserIDIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldAuthorUserID, vs...))
}

// AuthorUserIDNotIn applies the NotIn predicate on the "author_user_id" field.
func AuthorUserIDNotIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldAuthorUserID, vs...))
}

// AuthorRoleEQ applies the EQ predicate on the "author_role" field.
func AuthorRoleEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorRole, v))
}

// AuthorRoleNEQ applies the NEQ predicate on the "author_role" field.
func AuthorRoleNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldAuthorRole, v))
}

// AuthorRoleIn applies the In predicate on the "author_role" field.
func AuthorRoleIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldAuthorRole, vs...))
}

// AuthorRoleNotIn applies the NotIn predicate on the "author_role" field.
func AuthorRoleNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldAuthorRole, vs...))
}

// AuthorRoleGT applies the GT predicate on the "author_role" field.
func AuthorRoleGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldAuthorRole, v))
}

// AuthorRoleGTE applies the GTE predicate on the "author_role" field.
func AuthorRoleGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldAuthorRole, v))
}

// AuthorRoleLT applies the LT predicate on the "author_role" field.
func AuthorRoleLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldAuthorRole, v))
}

// AuthorRoleLTE applies the LTE predicate on the "author_role" field.
func AuthorRoleLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldAuthorRole, v))
}

// AuthorRoleContains applies the Contains predicate on the "author_role" field.
func AuthorRoleContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldAuthorRole, v))
}

// AuthorRoleHasPrefix applies the HasPrefix predicate on the "author_role" field.
func AuthorRoleHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldAuthorRole, v))
}

// AuthorRoleHasSuffix applies the HasSuffix predicate on the "author_role" field.
func AuthorRoleHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldAuthorRole, v))
}

// AuthorRoleEqualFold applies the EqualFold predicate on the "author_role" field.
func AuthorRoleEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldAuthorRole, v))
}

// AuthorRoleContainsFold applies the ContainsFold predicate on the "author_role" field.
func AuthorRoleContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldAuthorRole, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldBody, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.SupportTicket) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := newTicketStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuthor applies the HasEdge predicate on the "author" edge.
func HasAuthor() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorWith applies the HasEdge predicate on the "author" edge with a given conditions (other predicates).
func HasAuthorWith(preds ...predicate.User) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := newAuthorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttachments applies the HasEdge predicate on the "attachments" edge.
func HasAttachments() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentsWith applies the HasEdge predicate on the "attachments" edge with a given conditions (other predicates).
func HasAttachmentsWith(preds ...predicate.SupportTicketAttachment) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := newAttachmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.NotPredicates(p))
}
